version: "3.1"
services:
    db:
        container_name: nadasalama_db
        image: mariadb
        volumes:
            - ~/.DATABASE/nadasalama:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=nadasalama
            - MYSQL_USER=nadasalama
            - MYSQL_PASSWORD=secret
        ports:
            - 3306:3306

    adminer:
        container_name: nadasalama_adminer
        image: adminer
        ports:
            - 8080:8080

    web:
        container_name: nadasalama_web
        image: nginx
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/site.conf
        ports:
            - 80:80

    php:
        container_name: nadasalama_php
        image: sidi/php:fpm-alpine
        volumes:
            - .:/var/www
        environment:
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
        ports:
         - 9000:9000
